#!/bin/sh
set -e
echo "envs NEXT_PUBLIC_ALOKAI_MIDDLEWARE_API_URL: $NEXT_PUBLIC_ALOKAI_MIDDLEWARE_API_URL"
echo "envs NEXT_PUBLIC_ALOKAI_MULTISTORE_ENABLED: $NEXT_PUBLIC_ALOKAI_MULTISTORE_ENABLED"
echo "envs NEXT_PUBLIC_ALOKAI_MIDDLEWARE_CDN_CACHE_BUSTING_ID: $NEXT_PUBLIC_ALOKAI_MIDDLEWARE_CDN_CACHE_BUSTING_ID"
echo "envs NEXT_PUBLIC_IMAGE_LOADER_FETCH_URL: $NEXT_PUBLIC_IMAGE_LOADER_FETCH_URL"
echo "envs NEXT_PUBLIC_IMAGE_LOADER_UPLOAD_URL: $NEXT_PUBLIC_IMAGE_LOADER_UPLOAD_URL"
echo "envs NEXT_DEFAULT_HTML_CACHE_CONTROL: $NEXT_DEFAULT_HTML_CACHE_CONTROL"
echo "envs GIT_SHA: $GIT_SHA"
node ./server.js
